### ISSUE TITLE
Problem with Icon-Symbol in the Home-App when using a Unifi-Controller

### ISSUE THREAD

**Issue by g88704** [plainsane/homebridge-unifi-kids-cry#1]
Hi,

thanks for this nice homebridge plugin. I have a small problem/question.

Using the Home-app to block/unblock devices everything seems to work great. 

But if I use the Unifi-Controller app to block/unblock devices then only the text-status in the iOS Home-App will be updated correctly BUT the corresponding status-symbol in the Home-App shows only a spinning-wheel and the symbol will never be updated.

When opening the Home-App you can see in the homebridge log that your plugin receive the correct status (set with Unifi-controller) but as mentioned the status-symbol icon in the Home-App will not be updated (shows a spinning wheel only).

[8/14/2019, 7:19:28 AM] [UnifiMacBlocker] 00:11:22:33:44:55 blocked true
[8/14/2019, 7:19:52 AM] [UnifiMacBlocker] 00:11:22:33:44:55 blocked false

**Comment by plainsane** [comment]
I’ll look into this, sorry for the delay, have been busy

**Comment by plainsane** [comment]
fixed witth https://github.com/plainsane/homebridge-unifi-kids-cry/pull/2
