### ISSUE TITLE
Old "Unifi Kids Cry" plugin?

### ISSUE THREAD

**Issue by g88704** [plainsane/homebridge-unifi-kids-cry#4]
If you search for "unifi" plugins in the Homebridge app you will also be pointed to your old(?), same(?) Unifi Kids Cry plugin.

As far as I understood "Cry Kids" was the first, old name of the plugin but the active development is now under the "Unifi Mac Block" name.

Is this right? If yes I think it would be better to remove the Cry Kids plugin from a Homebridge search, otherwise new users get be confused which version to use.

Thanks again for your plugin and Kind Regards

**Comment by plainsane** [comment]
Yes, I’ll remove the old version

**Comment by plainsane** [comment]
Email sent to have them purge it

**Comment by plainsane** [comment]
its gone
