### ISSUE TITLE
UDM Pro compatability?

### ISSUE THREAD

**Issue by Movieaholic** [plainsane/homebridge-unifi-kids-cry#8]
Cant seem to get this going with UDM pro. Unifi controller no longer uses ports to separate protect and network controller anymore

**Comment by rloomans** [comment]
I've created a pull request that hacks in UDM Pro support: https://github.com/plainsane/homebridge-unifi-kids-cry/pull/7

Until this gets merged, you can remove @plainsane's version and do an `npm install git+https://github.com/rloomans/homebridge-unifi-kids-cry.git` to install my version.

You should be able to change your config remove the port number from the `base` and add `"unifios": true,` and it should work as before.

**Comment by Movieaholic** [comment]
Awsome worked like a charm Thanks
